version: "2.4"
# The server profiles used in this example are intended for use with edge versions of the product image only.

#-------------------------------------------------------------------------------------
#-
#-  PingFederate Console                         PingDataConsole (PingDirectory)
#-  --------------------                         -------------------------------
#-  https://localhost:9999/pingfederate/app      https://localhost:8443
#-    Username: administrator                        Server: pingdirectory
#-    Password: 2FederateM0re                      Username: administrator
#-                                                 Password: 2FederateM0re
#-
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://${GIT_USER}:${GIT_AT}@github.com/gmorgan-ping/workplace-provisioner.git
      - SERVER_PROFILE_PATH=server-profiles/pingfederate
      - VERBOSE=false
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - ${HOME}/devops_out_vols/provisioning/pf_out:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://${GIT_USER}:${GIT_AT}@github.com/gmorgan-ping/workplace-provisioner.git
      - SERVER_PROFILE_PATH=server-profiles/pingdirectory
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1636:636"
      - "1443:443"
      - "1389:389"
    networks:
      - pingnet
    volumes:
      - ${HOME}/devops_out_vols/provisioning/pd_out:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "8443:8443"
    networks:
      - pingnet

networks:
    pingnet:

