global:
  image:
    tag: "2010"
  addReleaseNameToResource: prepend
  ingress:
    enabled: true
    addReleaseNameToHost: subdomain
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

pingdelegator:
  enabled: true

pingdirectory:
  enabled: true
  envs:
    MAKELDIF_USERS: "1000"
  #   SERVER_PROFILE_URL: https://github.com/gmorgan-ping/workplace-provisioner.git
  #   SERVER_PROFILE_PATH: server-profiles/pingdirectory

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/gmorgan-ping/workplace-provisioner.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate



