global:
  image:
    tag: "edge"
  addReleaseNameToResource: none
  ingress:
    enabled: true
    addReleaseNameToHost: subdomain
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

# Future plans to add delegator
# Gitbook Delegator env vars (https://app.gitbook.com/@pingidentity-devops/s/devops/dockerimagesref/pingdelegator)
pingdelegator:
  enabled: false
  # envs:
  #   PF_ENGINE_PUBLIC_HOSTNAME=
  #   PF_ENGINE_PUBLIC_PORT=
  #   PF_DELEGATOR_CLIENTID=
  #   PD_ENGINE_PUBLIC_HOSTNAME=
  #   PD_ENGINE_PUBLIC_PORT=

pingdirectory:
  enabled: true
  envs:
    MAKELDIF_USERS: "1000"
  #   SERVER_PROFILE_URL: https://github.com/gmorgan-ping/workplace-provisioner.git
  #   SERVER_PROFILE_PATH: server-profiles/pingdirectory

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/gmorgan-ping/workplace-provisioner.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate

pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/gmorgan-ping/workplace-provisioner.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate

